-- Gerado a partir da aba Passeios
INSERT INTO passeios (cenario_id, descricao, cidade, fornecedor, moeda, valor_unitario, qtd_pessoas, transfer, link) VALUES
(11, 'Lagoa Bonita', 'Barreirinhas', 'Aventour', 'BRL', 110.00, 11, true, NULL),
(11, 'Circuito Atins', 'Barreirinhas', 'Aventour', 'BRL', 160.00, 11, true, NULL),
(11, 'Circuito Santo Amaro', 'Barreirinhas', 'Aventour', 'BRL', 200.00, 11, true, NULL),
(11, 'Caburé e Rio Preguiças', 'Barreirinhas', 'Aventour', 'BRL', 100.00, 11, true, NULL),
(11, 'Boia Cross Cardosa', 'Barreirinhas', 'Aventour', 'BRL', 100.00, 11, true, NULL),
(15, 'Parque das Aves', 'Foz do Iguaçu', 'Não informado', 'BRL', 110.00, 3, false, 'https://ingressos.parquedasaves.com.br/'),
(15, 'Cataratas do Iguaçu', 'Foz do Iguaçu', 'Não informado', 'BRL', 118.00, 3, false, 'https://tickets.cataratasdoiguacu.com.br/?utm_source=google&utm_medium=cpc&utm_campaign=pmax&gad_source=1&gad_campaignid=22434235363&gbraid=0AAAAAqu1oCqbgpgHnWFXsmx3Tc_v1oAeW&gclid=CjwKCAjwvZHTBhAlEiwA1ug5Pzii0snok4UXC3239fZFGoRnOvg17wQHNwJcrna0VH18KWb3Js5L_hoCElwQAvD_BwE'),
(16, 'Ilha Tour', 'Fernando de Noronha', 'Em Noronha', 'BRL', 280.00, 4, true, 'https://emnoronha.com.br/passeios/ilha-tour-coletivo'),
(17, 'Ilha Tour', 'Fernando de Noronha', 'Em Noronha', 'BRL', 280.00, 4, true, 'https://emnoronha.com.br/passeios/ilha-tour-coletivo'),
(18, 'Johnny Cay, Acuario, Haynes Cay e manguezais', 'San Andrés', 'Get Your Guide', 'BRL', 192.00, 1, true, NULL),
(22, 'Lagoa Bonita', 'Barreirinhas', 'Aventour', 'BRL', 110.00, 2, true, NULL),
(23, 'Lagoa Bonita', 'Barreirinhas', 'Aventour', 'BRL', 110.00, 2, true, NULL),
(24, 'Lagoa Bonita', 'Barreirinhas', 'Aventour', 'BRL', 110.00, 2, true, NULL),
(25, 'Lagoa Bonita', 'Barreirinhas', 'Aventour', 'BRL', 110.00, 2, true, NULL),
(22, 'Circuito Atins', 'Barreirinhas', 'Aventour', 'BRL', 160.00, 2, true, NULL),
(23, 'Circuito Atins', 'Barreirinhas', 'Aventour', 'BRL', 160.00, 2, true, NULL),
(24, 'Circuito Atins', 'Barreirinhas', 'Aventour', 'BRL', 160.00, 2, true, NULL),
(25, 'Circuito Atins', 'Barreirinhas', 'Aventour', 'BRL', 160.00, 2, true, NULL),
(22, 'Circuito Santo Amaro', 'Barreirinhas', 'Marreiros', 'BRL', 200.00, 2, true, NULL),
(23, 'Circuito Santo Amaro', 'Barreirinhas', 'Marreiros', 'BRL', 200.00, 2, true, NULL),
(24, 'Circuito Santo Amaro', 'Barreirinhas', 'Marreiros', 'BRL', 200.00, 2, true, NULL),
(25, 'Circuito Santo Amaro', 'Barreirinhas', 'Marreiros', 'BRL', 200.00, 2, true, NULL),
(22, 'Delta do Parnaíba', 'Parnaíba', 'Rota Combo', 'BRL', 100.00, 2, true, NULL),
(23, 'Delta do Parnaíba', 'Parnaíba', 'Rota Combo', 'BRL', 100.00, 2, true, NULL),
(24, 'Delta do Parnaíba', 'Parnaíba', 'Rota Combo', 'BRL', 100.00, 2, true, NULL),
(25, 'Delta do Parnaíba', 'Parnaíba', 'Rota Combo', 'BRL', 100.00, 2, true, NULL),
(22, 'Lado Leste', 'Jeri', 'Loucos por Jeri', 'BRL', 70.00, 2, true, NULL),
(23, 'Lado Leste', 'Jeri', 'Loucos por Jeri', 'BRL', 70.00, 2, true, NULL),
(24, 'Lado Leste', 'Jeri', 'Loucos por Jeri', 'BRL', 70.00, 2, true, NULL),
(25, 'Lado Leste', 'Jeri', 'Loucos por Jeri', 'BRL', 70.00, 2, true, NULL),
(22, 'Lado Oeste', 'Jeri', 'Loucos por Jeri', 'BRL', 70.00, 2, true, NULL),
(23, 'Lado Oeste', 'Jeri', 'Loucos por Jeri', 'BRL', 70.00, 2, true, NULL),
(24, 'Lado Oeste', 'Jeri', 'Loucos por Jeri', 'BRL', 70.00, 2, true, NULL),
(25, 'Lado Oeste', 'Jeri', 'Loucos por Jeri', 'BRL', 70.00, 2, true, NULL),
(26, 'Ilha do Campeche Saída da Barra da Lagoa', 'Florianópolis', 'Ilha da Magia', 'BRL', 200.00, 2, false, 'https://ilhadamagiaonline.com.br/passeio/ilha-do-campeche-passeio-saida-barra-da-lagoa/'),
(27, 'Ilha do Campeche Saída da Barra da Lagoa', 'Florianópolis', 'Ilha da Magia', 'BRL', 200.00, 2, false, 'https://ilhadamagiaonline.com.br/passeio/ilha-do-campeche-passeio-saida-barra-da-lagoa/'),
(28, 'Ilha do Campeche Saída da Barra da Lagoa', 'Florianópolis', 'Ilha da Magia', 'BRL', 200.00, 2, false, 'https://ilhadamagiaonline.com.br/passeio/ilha-do-campeche-passeio-saida-barra-da-lagoa/'),
(29, 'Lancha Maragogi', 'Maragogi', 'Caribe Maragogi', 'BRL', 130.00, 2, false, NULL),
(30, 'Lancha Maragogi', 'Maragogi', 'Caribe Maragogi', 'BRL', 130.00, 2, false, NULL),
(31, 'Lancha Maragogi', 'Maragogi', 'Caribe Maragogi', 'BRL', 130.00, 2, false, NULL),
(29, 'Buggy Ponta a Ponta', 'Porto de Galinhas', 'Buggy Tour', 'BRL', 247.50, 2, true, NULL),
(30, 'Buggy Ponta a Ponta', 'Porto de Galinhas', 'Buggy Tour', 'BRL', 247.50, 2, true, NULL),
(31, 'Buggy Ponta a Ponta', 'Porto de Galinhas', 'Buggy Tour', 'BRL', 247.50, 2, true, NULL),
(32, 'Buggy Genipabu', 'Natal', 'Natal Pipa', 'BRL', 145.00, 2, true, 'https://natalpipa.com.br/'),
(33, 'Buggy Genipabu', 'Natal', 'Natal Pipa', 'BRL', 145.00, 2, true, 'https://natalpipa.com.br/'),
(34, 'Buggy Genipabu', 'Natal', 'Natal Pipa', 'BRL', 145.00, 2, true, 'https://natalpipa.com.br/'),
(35, 'Buggy Genipabu', 'Natal', 'Natal Pipa', 'BRL', 145.00, 2, true, 'https://natalpipa.com.br/'),
(32, 'Piscinas Naturais dos Seixas', 'João Pessoa', 'Nordestine-se', 'BRL', 60.00, 2, false, NULL),
(33, 'Piscinas Naturais dos Seixas', 'João Pessoa', 'Nordestine-se', 'BRL', 60.00, 2, false, NULL),
(34, 'Piscinas Naturais dos Seixas', 'João Pessoa', 'Nordestine-se', 'BRL', 60.00, 2, false, NULL),
(35, 'Piscinas Naturais dos Seixas', 'João Pessoa', 'Nordestine-se', 'BRL', 60.00, 2, false, NULL),
(36, 'Passeio de Escuna Búzios', 'Búzios', 'Búzios Trip Tour', 'BRL', 70.00, 2, false, 'https://buziostriptour.com/tours/passeio-de-escuna-em-buzios/'),
(37, 'Passeio de Escuna Búzios', 'Búzios', 'Búzios Trip Tour', 'BRL', 70.00, 2, false, 'https://buziostriptour.com/tours/passeio-de-escuna-em-buzios/'),
(38, 'Passeio de Escuna Búzios', 'Búzios', 'Búzios Trip Tour', 'BRL', 70.00, 2, false, 'https://buziostriptour.com/tours/passeio-de-escuna-em-buzios/'),
(39, 'Passeio de Escuna Búzios', 'Búzios', 'Búzios Trip Tour', 'BRL', 70.00, 2, false, 'https://buziostriptour.com/tours/passeio-de-escuna-em-buzios/'),
(36, 'Passeio de Escuna Arraial do Cabo', 'Arraial do Cabo', 'Efraim Turismo', 'BRL', 150.00, 2, false, 'https://efraimturismo.com/passeio-de-barco-1757'),
(37, 'Passeio de Escuna Arraial do Cabo', 'Arraial do Cabo', 'Efraim Turismo', 'BRL', 150.00, 2, false, 'https://efraimturismo.com/passeio-de-barco-1757'),
(38, 'Passeio de Escuna Arraial do Cabo', 'Arraial do Cabo', 'Efraim Turismo', 'BRL', 150.00, 2, false, 'https://efraimturismo.com/passeio-de-barco-1757'),
(39, 'Passeio de Escuna Arraial do Cabo', 'Arraial do Cabo', 'Efraim Turismo', 'BRL', 150.00, 2, false, 'https://efraimturismo.com/passeio-de-barco-1757'),
(57, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 269.00, 2, false, NULL),
(58, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 269.00, 2, false, NULL),
(57, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 31.00, 1, false, NULL),
(58, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 31.00, 1, false, NULL),
(57, 'Estância Mimosa', 'Bonito', 'Bonito Eco Tour', 'BRL', 340.00, 2, false, NULL),
(58, 'Estância Mimosa', 'Bonito', 'Bonito Eco Tour', 'BRL', 340.00, 2, false, NULL),
(57, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 145.00, 2, false, NULL),
(58, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 145.00, 2, false, NULL),
(57, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 110.00, 1, false, NULL),
(58, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 110.00, 1, false, NULL),
(57, 'Boca da Onça - Meia Trilha Buraco do Macaco', 'Bonito', 'Bonito Eco Tour', 'BRL', 430.00, 2, false, NULL),
(58, 'Boca da Onça - Meia Trilha Buraco do Macaco', 'Bonito', 'Bonito Eco Tour', 'BRL', 430.00, 2, false, NULL),
(57, 'Refúgio da Barra', 'Bonito', 'Bonito Eco Tour', 'BRL', 90.00, 2, false, NULL),
(58, 'Refúgio da Barra', 'Bonito', 'Bonito Eco Tour', 'BRL', 90.00, 2, false, NULL),
(59, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 269.00, 2, false, NULL),
(60, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 269.00, 2, false, NULL),
(61, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 269.00, 2, false, NULL),
(59, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 31.00, 1, false, NULL),
(60, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 31.00, 1, false, NULL),
(61, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 31.00, 1, false, NULL),
(59, 'Estância Mimosa', 'Bonito', 'Bonito Eco Tour', 'BRL', 340.00, 2, false, NULL),
(60, 'Estância Mimosa', 'Bonito', 'Bonito Eco Tour', 'BRL', 340.00, 2, false, NULL),
(61, 'Estância Mimosa', 'Bonito', 'Bonito Eco Tour', 'BRL', 340.00, 2, false, NULL),
(59, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 145.00, 2, false, NULL),
(60, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 145.00, 2, false, NULL),
(61, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 145.00, 2, false, NULL),
(59, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 110.00, 1, false, NULL),
(60, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 110.00, 1, false, NULL),
(61, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 110.00, 1, false, NULL),
(59, 'Boca da Onça - Meia Trilha Buraco do Macaco', 'Bonito', 'Bonito Eco Tour', 'BRL', 430.00, 2, false, NULL),
(60, 'Boca da Onça - Meia Trilha Buraco do Macaco', 'Bonito', 'Bonito Eco Tour', 'BRL', 430.00, 2, false, NULL),
(61, 'Boca da Onça - Meia Trilha Buraco do Macaco', 'Bonito', 'Bonito Eco Tour', 'BRL', 430.00, 2, false, NULL),
(59, 'Refúgio da Barra', 'Bonito', 'Bonito Eco Tour', 'BRL', 90.00, 2, false, NULL),
(60, 'Refúgio da Barra', 'Bonito', 'Bonito Eco Tour', 'BRL', 90.00, 2, false, NULL),
(61, 'Refúgio da Barra', 'Bonito', 'Bonito Eco Tour', 'BRL', 90.00, 2, false, NULL),
(54, 'Lancha Maragogi', 'Maragogi', 'Caribe Maragogi', 'BRL', 130.00, 2, false, NULL),
(55, 'Lancha Maragogi', 'Maragogi', 'Caribe Maragogi', 'BRL', 130.00, 2, false, NULL),
(56, 'Lancha Maragogi', 'Maragogi', 'Caribe Maragogi', 'BRL', 130.00, 2, false, NULL),
(54, 'Buggy Ponta a Ponta', 'Porto de Galinhas', 'Buggy Tour', 'BRL', 247.50, 2, true, NULL),
(55, 'Buggy Ponta a Ponta', 'Porto de Galinhas', 'Buggy Tour', 'BRL', 247.50, 2, true, NULL),
(56, 'Buggy Ponta a Ponta', 'Porto de Galinhas', 'Buggy Tour', 'BRL', 247.50, 2, true, NULL),
(54, 'Buggy Litoral Norte Premium', 'Maragogi', 'Caribe Maragogi', 'BRL', 200.00, 1, true, NULL),
(55, 'Buggy Litoral Norte Premium', 'Maragogi', 'Caribe Maragogi', 'BRL', 200.00, 1, true, NULL),
(56, 'Buggy Litoral Norte Premium', 'Maragogi', 'Caribe Maragogi', 'BRL', 200.00, 1, true, NULL),
(54, 'Praia do Gunga', 'Maceió', 'Maresul', 'BRL', 43.20, 2, true, NULL),
(55, 'Praia do Gunga', 'Maceió', 'Maresul', 'BRL', 43.20, 2, true, NULL),
(56, 'Praia do Gunga', 'Maceió', 'Maresul', 'BRL', 43.20, 2, true, NULL),
(54, 'Praia do Gunga', 'Maceió', 'Maresul', 'BRL', 33.60, 1, true, NULL),
(55, 'Praia do Gunga', 'Maceió', 'Maresul', 'BRL', 33.60, 1, true, NULL),
(56, 'Praia do Gunga', 'Maceió', 'Maresul', 'BRL', 33.60, 1, true, NULL),
(54, 'São Miguel dos Milagres', 'Maceió', 'Maresul', 'BRL', 79.20, 2, true, NULL),
(55, 'São Miguel dos Milagres', 'Maceió', 'Maresul', 'BRL', 79.20, 2, true, NULL),
(56, 'São Miguel dos Milagres', 'Maceió', 'Maresul', 'BRL', 79.20, 2, true, NULL),
(54, 'São Miguel dos Milagres', 'Maceió', 'Maresul', 'BRL', 61.60, 1, true, NULL),
(55, 'São Miguel dos Milagres', 'Maceió', 'Maresul', 'BRL', 61.60, 1, true, NULL),
(56, 'São Miguel dos Milagres', 'Maceió', 'Maresul', 'BRL', 61.60, 1, true, NULL),
(54, 'Praia do Francês', 'Maceió', 'Maresul', 'BRL', 43.20, 2, true, NULL),
(55, 'Praia do Francês', 'Maceió', 'Maresul', 'BRL', 43.20, 2, true, NULL),
(56, 'Praia do Francês', 'Maceió', 'Maresul', 'BRL', 43.20, 2, true, NULL),
(54, 'Praia do Francês', 'Maceió', 'Maresul', 'BRL', 33.60, 1, true, NULL),
(55, 'Praia do Francês', 'Maceió', 'Maresul', 'BRL', 33.60, 1, true, NULL),
(56, 'Praia do Francês', 'Maceió', 'Maresul', 'BRL', 33.60, 1, true, NULL),
(42, 'Buggy Ponta a Ponta', 'Porto de Galinhas', 'Buggy Tour', 'BRL', 495.00, 1, true, NULL),
(43, 'Buggy Ponta a Ponta', 'Porto de Galinhas', 'Buggy Tour', 'BRL', 495.00, 1, true, NULL),
(44, 'Buggy Ponta a Ponta', 'Porto de Galinhas', 'Buggy Tour', 'BRL', 495.00, 1, true, NULL),
(42, 'Praia do Gunga', 'Maceió', 'Maresul', 'BRL', 43.20, 2, true, NULL),
(43, 'Praia do Gunga', 'Maceió', 'Maresul', 'BRL', 43.20, 2, true, NULL),
(44, 'Praia do Gunga', 'Maceió', 'Maresul', 'BRL', 43.20, 2, true, NULL),
(42, 'São Miguel dos Milagres', 'Maceió', 'Maresul', 'BRL', 79.20, 2, true, NULL),
(43, 'São Miguel dos Milagres', 'Maceió', 'Maresul', 'BRL', 79.20, 2, true, NULL),
(44, 'São Miguel dos Milagres', 'Maceió', 'Maresul', 'BRL', 79.20, 2, true, NULL),
(42, 'Maragogi c/ piscinas', 'Maceió', 'Maresul', 'BRL', 210.00, 2, true, NULL),
(43, 'Maragogi c/ piscinas', 'Maceió', 'Maresul', 'BRL', 210.00, 2, true, NULL),
(44, 'Maragogi c/ piscinas', 'Maceió', 'Maresul', 'BRL', 210.00, 2, true, NULL),
(54, 'Praia dos Carneiros Bora Bora (Lancha)', 'Porto de Galinhas', 'Brasil Tur Passeios', 'BRL', 190.00, 2, true, NULL),
(55, 'Praia dos Carneiros Bora Bora (Lancha)', 'Porto de Galinhas', 'Brasil Tur Passeios', 'BRL', 190.00, 2, true, NULL),
(56, 'Praia dos Carneiros Bora Bora (Lancha)', 'Porto de Galinhas', 'Brasil Tur Passeios', 'BRL', 190.00, 2, true, NULL),
(66, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 269.00, 2, false, NULL),
(67, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 269.00, 2, false, NULL),
(68, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 269.00, 2, false, NULL),
(66, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 31.00, 1, false, NULL),
(67, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 31.00, 1, false, NULL),
(68, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 31.00, 1, false, NULL),
(66, 'Estância Mimosa', 'Bonito', 'Bonito Eco Tour', 'BRL', 340.00, 2, false, NULL),
(67, 'Estância Mimosa', 'Bonito', 'Bonito Eco Tour', 'BRL', 340.00, 2, false, NULL),
(68, 'Estância Mimosa', 'Bonito', 'Bonito Eco Tour', 'BRL', 340.00, 2, false, NULL),
(66, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 145.00, 2, false, NULL),
(67, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 145.00, 2, false, NULL),
(68, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 145.00, 2, false, NULL),
(66, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 110.00, 1, false, NULL),
(67, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 110.00, 1, false, NULL),
(68, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 110.00, 1, false, NULL),
(66, 'Boca da Onça - Meia Trilha Buraco do Macaco', 'Bonito', 'Bonito Eco Tour', 'BRL', 430.00, 2, false, NULL),
(67, 'Boca da Onça - Meia Trilha Buraco do Macaco', 'Bonito', 'Bonito Eco Tour', 'BRL', 430.00, 2, false, NULL),
(68, 'Boca da Onça - Meia Trilha Buraco do Macaco', 'Bonito', 'Bonito Eco Tour', 'BRL', 430.00, 2, false, NULL),
(66, 'Refúgio da Barra', 'Bonito', 'Bonito Eco Tour', 'BRL', 90.00, 2, false, NULL),
(67, 'Refúgio da Barra', 'Bonito', 'Bonito Eco Tour', 'BRL', 90.00, 2, false, NULL),
(68, 'Refúgio da Barra', 'Bonito', 'Bonito Eco Tour', 'BRL', 90.00, 2, false, NULL),
(66, 'Safari', 'Bonito', 'Bonito Eco Tour', 'BRL', 300.00, 2, false, NULL),
(67, 'Safari', 'Bonito', 'Bonito Eco Tour', 'BRL', 300.00, 2, false, NULL),
(68, 'Safari', 'Bonito', 'Bonito Eco Tour', 'BRL', 300.00, 2, false, NULL),
(66, 'Safari criança', 'Bonito', 'Bonito Eco Tour', 'BRL', 202.00, 1, false, NULL),
(67, 'Safari criança', 'Bonito', 'Bonito Eco Tour', 'BRL', 202.00, 1, false, NULL),
(68, 'Safari criança', 'Bonito', 'Bonito Eco Tour', 'BRL', 202.00, 1, false, NULL),
(69, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 269.00, 2, false, NULL),
(70, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 269.00, 2, false, NULL),
(69, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 31.00, 1, false, NULL),
(70, 'Barra do Sucuri', 'Bonito', 'Bonito Eco Tour', 'BRL', 31.00, 1, false, NULL),
(69, 'Estância Mimosa', 'Bonito', 'Bonito Eco Tour', 'BRL', 340.00, 2, false, NULL),
(70, 'Estância Mimosa', 'Bonito', 'Bonito Eco Tour', 'BRL', 340.00, 2, false, NULL),
(69, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 145.00, 2, false, NULL),
(70, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 145.00, 2, false, NULL),
(69, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 110.00, 1, false, NULL),
(70, 'Eco Park Porto da Ilha - Boia Cross', 'Bonito', 'Bonito Eco Tour', 'BRL', 110.00, 1, false, NULL),
(69, 'Boca da Onça - Meia Trilha Buraco do Macaco', 'Bonito', 'Bonito Eco Tour', 'BRL', 430.00, 2, false, NULL),
(70, 'Boca da Onça - Meia Trilha Buraco do Macaco', 'Bonito', 'Bonito Eco Tour', 'BRL', 430.00, 2, false, NULL),
(69, 'Refúgio da Barra', 'Bonito', 'Bonito Eco Tour', 'BRL', 90.00, 2, false, NULL),
(70, 'Refúgio da Barra', 'Bonito', 'Bonito Eco Tour', 'BRL', 90.00, 2, false, NULL),
(69, 'Day use Safari', 'Bonito', 'Bonito Eco Tour', 'BRL', 438.00, 2, false, NULL),
(70, 'Day use Safari', 'Bonito', 'Bonito Eco Tour', 'BRL', 438.00, 2, false, NULL),
(69, 'Day use Safari criança', 'Bonito', 'Bonito Eco Tour', 'BRL', 300.00, 1, false, NULL),
(70, 'Day use Safari criança', 'Bonito', 'Bonito Eco Tour', 'BRL', 300.00, 1, false, NULL),
(69, 'Praia da Figueira', 'Bonito', 'Bonito Eco Tour', 'BRL', 119.00, 2, false, NULL),
(70, 'Praia da Figueira', 'Bonito', 'Bonito Eco Tour', 'BRL', 119.00, 2, false, NULL),
(71, 'Parrachos de Maracajaú', 'Natal', 'Natal Pipa', 'BRL', 170.00, 2, true, NULL),
(71, 'Buggy Genipabu', 'Natal', 'Natal Pipa', 'BRL', 145.00, 2, true, NULL),
(71, 'Bate e Volta Pipa', 'Natal', 'Natal Pipa', 'BRL', 65.00, 2, true, 'https://www.natalpipa.com.br/'),
(72, 'Quadriciclo Pipa', 'Pipa', 'Natal Pipa', 'BRL', 270.00, 1, true, 'https://natalpipa.com.br/passeio/passeio-de-quadriciclo-pipa'),
(73, 'Quadriciclo Pipa', 'Pipa', 'Natal Pipa', 'BRL', 270.00, 1, true, 'https://natalpipa.com.br/passeio/passeio-de-quadriciclo-pipa'),
(74, 'Combo Litoral norte', 'João Pessoa', 'Nordestine-se', 'BRL', 170.00, 2, true, NULL),
(74, 'Piscinas Naturais dos Seixas', 'João Pessoa', 'Nordestine-se', 'BRL', 60.00, 2, true, NULL),
(74, 'Combo Litoral Sul', 'João Pessoa', 'Nordestine-se', 'BRL', 190.00, 2, true, NULL),
(75, 'Volta à Ilha', 'Morro de São Paulo', 'Passeios Morro', 'BRL', 350.00, 2, false, 'https://passeiosmorro.com.br/passeios/volta-a-ilha'),
(76, 'Ilha Tour', 'Fernando de Noronha', 'Em Noronha', 'BRL', 280.00, 2, true, NULL),
(77, 'Johnny Cay, Acuario, Haynes Cay e manguezais', 'San Andrés', 'Get Your Guide', 'USD', 36.38, 2, true, NULL),
(78, 'Isla Saona', 'Punta Cana', 'Decolar', 'BRL', 350.00, 2, true, 'https://www.decolar.com/atracoes-turisticas/d-PAM_PUJ_58710/ilha+saona+em+catamara+ou+lancha+tudo+incluido-punta+cana?modalityId=UFVKfDU4NzEwfDIzMzAwM3xGSVhFRA'),
(79, 'Quadriciclo Jeri', 'Jeri', 'Loucos por Jeri', 'BRL', 550.00, 1, true, NULL),
(79, 'Lado Oeste', 'Jeri', 'Loucos por Jeri', 'BRL', 70.00, 2, true, NULL),
(79, 'Alchymist Beach Club', 'Jeri', 'Loucos por Jeri', 'BRL', 130.00, 2, true, NULL),
(80, 'Buggy Genipabu', 'Natal', 'Natal Pipa', 'BRL', 145.00, 2, true, NULL),
(81, 'Buggy Genipabu', 'Natal', 'Natal Pipa', 'BRL', 145.00, 2, true, NULL),
(82, 'Buggy Genipabu', 'Natal', 'Natal Pipa', 'BRL', 145.00, 2, true, NULL),
(80, 'Quadriciclo Pipa', 'Pipa', 'Natal Pipa', 'BRL', 270.00, 1, true, 'https://natalpipa.com.br/passeio/passeio-de-quadriciclo-pipa'),
(81, 'Quadriciclo Pipa', 'Pipa', 'Natal Pipa', 'BRL', 270.00, 1, true, 'https://natalpipa.com.br/passeio/passeio-de-quadriciclo-pipa'),
(82, 'Quadriciclo Pipa', 'Pipa', 'Natal Pipa', 'BRL', 270.00, 1, true, 'https://natalpipa.com.br/passeio/passeio-de-quadriciclo-pipa'),
(80, 'Piscinas Naturais dos Seixas', 'João Pessoa', 'Nordestine-se', 'BRL', 60.00, 2, true, NULL),
(81, 'Piscinas Naturais dos Seixas', 'João Pessoa', 'Nordestine-se', 'BRL', 60.00, 2, true, NULL),
(82, 'Piscinas Naturais dos Seixas', 'João Pessoa', 'Nordestine-se', 'BRL', 60.00, 2, true, NULL),
(83, 'Praia do Gunga', 'Maceió', 'Maresul', 'BRL', 43.20, 2, true, NULL),
(83, 'São Miguel dos Milagres', 'Maceió', 'Maresul', 'BRL', 79.20, 2, true, NULL),
(83, 'Buggy São Miguel dos Milagres', 'Maceió', 'Jr Buggy Milagres /', 'BRL', 250.00, 1, true, NULL),
(83, 'Praia do Francês', 'Maceió', 'Maresul', 'BRL', 43.20, 2, true, NULL),
(83, 'Maragogi c/ piscinas', 'Maceió', 'Maresul', 'BRL', 210.00, 2, true, NULL),
(87, 'Praia dos Carneiros Bora Bora (Lancha)', 'Porto de Galinhas', 'Brasil Tur Passeios', 'BRL', 190.00, 3, true, NULL);
